Filtering sounds
TGLuis/Youpidapp pull request #12
Opened 2020-11-18 22:18 UTC by Jimvy

Fixes #3 

Possible amélioration : effectuer la recherche dans les transcripts des sons.

Mais j'aimerais d'abord savoir si vous n'avez pas de problèmes de performance/fluidité sur vos téléphones avec cette version (c'est pas comme si le truc fait un contains en O(nm) sur 55 sons à chaque caractère ^^).

(Feature request : mettre le son "Damnation" à part <3 )

2020-11-19 09:03 UTC, TGLuis reviewed
LGTM :D juste une question sur les id à voir plus bas!

2020-11-19 09:03 UTC, TGLuis commented on app/src/main/java/data/Sound.kt
> -        }
à quoi ça sert de mettre un id dans le fichier JSON si de toute façon chaque fois qu'on veut récupérer le texte on va chercher l'identifier dans les resources??? On devrait pas juste mettre:
``
var id: Int = 0,
``
et puis le set au moment où on fait le init?? comme ça 1: on va le chercher 1 fois dans les resources, 2: on n'a pas besoin de le mettre dans le json.

2020-11-19 09:22 UTC, Jimvy commented on app/src/main/java/data/Sound.kt
> -        }
Justement, j'ai supprimé le get() vu qu'on passe le displayText en argument du constructeur.
Pour l'ID : c'est vrai qu'il ne sert un peu à rien pour l'instant, mais bon, c'est pas méga ennuyant

2020-11-20 19:44 UTC, FrancoisDuchene reviewed
Ça me semble bien. J'ai quelques commentaires à propos de certains choix de design mais sinon ça me semble OK

2020-11-20 19:44 UTC, FrancoisDuchene commented on app/src/main/java/lufra/youpidapp/MainActivity.kt
> +            "soundbox", "buzzbox" -> {
Je comprend pas trop l'utilité d'avoir séparé le *home* en *"soundbox"* et *"buzzbox"* alors qu'au final c'est le même menu dans tous les cas

2020-11-20 19:44 UTC, FrancoisDuchene commented on app/src/main/java/lufra/youpidapp/Helper.kt
> +                it.getString("displaytext"),
Il sert à quelque chose l'*id* ? parce que le *name* sert déjà de clé primaire

2020-11-20 21:31 UTC, Jimvy commented on app/src/main/java/lufra/youpidapp/MainActivity.kt
> +            "soundbox", "buzzbox" -> {
Justement, ce n'est plus le même menu, il y a le bouton de la recherche dans la soundbox (voir le code au-dessus)

2020-11-20 21:33 UTC, Jimvy commented on app/src/main/java/lufra/youpidapp/Helper.kt
> +                it.getString("displaytext"),
On en discutait avec Luis, en effet il ne sert à rien pour le moment, et en théorie le name devrait être unique.

J'en déduis que vous souhaitez tous les deux son élimination ? 😅

2020-11-20 22:39 UTC, Jimvy commented
En vrai si, il y a une utilité (cachée) à l'ID : ça permet de trier les boutons différemment en fonction de si l'ID est > 0 ou < 0.
A la base je comptais utiliser ça pour pouvoir mettre le bouton random dans la RecyclerView (pour qu'il puisse scroller avec la liste, ainsi que pour qu'il puisse disparaître de la liste quand on filtre) tout en évitant de devoir lui trouver un nom : en gros le bouton random aurait été associé à un son dans la mSoundsList avec un ID = -1 et cela aurait permis, via le `mComparator`, de le remonter tout en haut de la liste.

2020-11-21 12:42 UTC, FrancoisDuchene commented on app/src/main/java/lufra/youpidapp/Helper.kt
> +                it.getString("displaytext"),
Ben ça rajoute de la complexité pour rien je trouve, si tu trouves qu'il a une utilité, on peut le laisser

2020-11-21 12:45 UTC, FrancoisDuchene commented
> En vrai si, il y a une utilité (cachée) à l'ID : ça permet de trier les boutons différemment en fonction de si l'ID est > 0 ou < 0.
Genre pour trier par ordre croissant ou décroissant ? Parce qu'il y a déjà l'ordre alphabétique
> A la base je comptais utiliser ça pour pouvoir mettre le bouton random dans la RecyclerView (pour qu'il puisse scroller avec la liste, ainsi que pour qu'il puisse disparaître de la liste quand on filtre) tout en évitant de devoir lui trouver un nom : en gros le bouton random aurait été associé à un son dans la mSoundsList avec un ID = -1 et cela aurait permis, via le `mComparator`, de le remonter tout en haut de la liste.
ben si le bouton random il a un nom, c'est le bouton "random". Je crois que je vois ce que tu veux faire avec comparator, ouais ok ça peut être utile pour ça

2020-11-21 13:47 UTC, TGLuis commented
Du coup faudrait soit, implémenter ce que tu propose, soit le mettre en issue pour qu'on aie une trace de cet id qui doit servir à cette future fonctionnalité. Quand un des deux sera fait on pourra merge la PR ! En soit on pourrait aussi dire que le bouton random reste fixe mais ne propose que les sons qui sont triés par le recherche. ça demanderait un changement sur la manière de faire le playRandom mais ça peut être sympa...

2020-11-21 14:01 UTC, Jimvy commented
@TGLuis j'avoue que le bouton random qui play random que parmi les sons affichés ça pourrait être sympa 😮 mais compliqué.
Actuellement la seule vraie raison que je voie pour faire ce truc de bouton random dans la liste c'est en mode paysage sur téléphone (où il y a vraiment pas la place).

Du coup je vire l'ID, ça vous va ? Puis de toute façon, tant qu'on a l'historique des commits on aura une trace de ça 😛
Je vire aussi l'ID de la DB JSON ?

2020-11-21 14:31 UTC, TGLuis commented
C'est compliqué, compliqué, compliqué, compliqué (mais stylé). Mais pour moi on peut virer l'id de partout, @FrancoisDuchene  ton avis?

2020-11-23 21:30 UTC, FrancoisDuchene commented
on peut virer l'id pour moi

2020-11-23 21:31 UTC, FrancoisDuchene approved these changes

2020-11-23 21:31 UTC, FrancoisDuchene requested changes
remove id plz :(

2020-11-23 22:25 UTC, TGLuis approved these changes
Very good

2020-11-23 22:25 UTC, FrancoisDuchene approved these changes
C'était compliqué compliqué compliqué compliqué COMPLIQUÉ

2020-11-23 22:25 UTC, merged