Je teste des trucs debiles
TGLuis/Youpidapp pull request #25
Opened 2021-01-22 15:29 UTC by FrancoisDuchene

# Easter Eggs
J'ai ajouté quelques easter eggs
- Quand on appuie sur le bouton EPL, y a des avions en papier qui apparaissent. Si on appuie plusieurs fois de suite, il y en a deux qui apparaissent de deux cotés à la fois.
- Quand on ouvre un lien youtube via le lien vers sa chaine ou via le bouton covid, des sons sont lancés.
- Quand on appuie longuement sur le bouton comu, (spoiler) une photo de chat triste et une musique triste s'affichent/sont jouées pendant 60 secondes. Parce qu'un autre son est joué pendant la lecture de la musique, le mode de lecture est changé en "plusieurs sons en même temps" (sinon le nouveau son coupait la musique). La musique est libre de droit. Conformément aux demandes du propriétaire de la musique, une mention vers la licence a été ajoutée dans le repo github et dans un fichier séparé.

2021-01-24 18:10 UTC, Jimvy reviewed
Faut que tu rebases/merges.

Comme suggéré dans un commentaire, peut-être qu'il faudrait refactor les méthodes pour qu'on puisse passer directement l'id de resources, plutôt que passer un (pointeur vers) string qui doit ensuite être passé dans une Map. Mais later...

La musique est un peu longue, et comme on sait, les blagues les plus courtes sont les meilleures ;)
Aussi, j'ai pas bien compris, mais pourquoi on passe le mode de lecture en "l'un après l'autre", et pas en "en même temps" ?

2021-01-24 18:10 UTC, Jimvy commented on app/src/main/java/lufra/youpidapp/Discotheque.kt
> +    private fun playOne(name: String, soundList: HashMap<String, Int>): Int {
```suggestion
    /**
     * Joue le son "name" en mode "un seul à la fois".
     * @param name  le nom du son à jouer
     * @param soundList  une Map de nom de son (valides) vers un id de resource de son (valide).
     */
    private fun playOne(name: String, soundList: Map<String, Int> = all): Int {
```
En vrai il faudrait peut-être refactor ça et juste passer l'entier `soundList[name]!!`...

2021-01-24 18:10 UTC, Jimvy commented on app/src/main/java/data/PaperPlane.kt
> +class PaperPlane(
Nitpicking : cette classe devrait plutôt se situer dans `BoiteFragment.kt` en tant qu'inner class vu qu'elle n'est utilisée que là, et parce qu'elle contient une View, donc ce n'est pas vraiment du data, mais du View (ou du ViewHolder ^^).

2021-01-24 18:10 UTC, Jimvy commented on app/src/main/java/fragments/BoiteFragment.kt
> +            context.discotheque.setType(2)
On devrait avoir une constante "PLAY_SEQUENTIAL" pour que ce soit plus clair ^^

2021-01-24 21:50 UTC, TGLuis requested changes
Plusieurs bonnes idées, qques corrections légères à faire d'après moi.

2021-01-24 21:50 UTC, TGLuis commented on app/src/main/java/fragments/BoiteFragment.kt
> +import android.animation.*
Optimisation des imports? :p

2021-01-24 21:50 UTC, TGLuis commented on app/src/main/java/fragments/BoiteFragment.kt
> +import java.util.*
Ici aussi, et d'ailleurs si le java util est importé juste pour le random, je pense que Kotlin en a un et que c'est mieux de pas utiliser les librairies java si on fait du kotlin.
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.random/-random/

2021-01-24 21:50 UTC, TGLuis commented on app/src/main/java/fragments/BoiteFragment.kt
> +            context.discotheque.setType(2)
C'est vrai mais ça n'a rien à voir avec cette PR :p

2021-01-24 21:50 UTC, TGLuis commented on app/src/main/java/lufra/youpidapp/Discotheque.kt
>  import java.util.*
Tant qu'on y est peut-être aussi refactor ici :p (je sais que c'est pas de cette pr mais bon :p )

2021-01-24 22:30 UTC, FrancoisDuchene commented on app/src/main/java/lufra/youpidapp/Discotheque.kt
> +    private fun playOne(name: String, soundList: HashMap<String, Int>): Int {
En effet ça semble plus judicieux (j'avais oublié qu'en Kotlin on pouvait mettre des paramètres par défaut 😅 ). je vais refractor pour directement passer les id, ça semble plus logique que passer un hashmap

2021-01-24 22:33 UTC, FrancoisDuchene commented on app/src/main/java/data/PaperPlane.kt
> +class PaperPlane(
J'ai bougé la classe hors de *BoiteFragment* parce que je trouvais que ça faisait déjà désordre dedans. Mais c'est vrai qu'elle est suffisamment petite pour que ça soit inutile de la mettre à part. (par contre je ne m'empêche pas de la redéplacer en dehors de *Boitefragment* dans le future pour réutiliser les avions autre part)

2021-01-24 22:35 UTC, FrancoisDuchene commented on app/src/main/java/fragments/BoiteFragment.kt
> +            context.discotheque.setType(2)
Je vais ajouter une issue là-dessus (pour pas oublier)

2021-01-24 22:37 UTC, FrancoisDuchene commented on app/src/main/java/fragments/BoiteFragment.kt
> +import android.animation.*
arf merci android studio :P

2021-01-24 22:39 UTC, FrancoisDuchene commented on app/src/main/java/fragments/BoiteFragment.kt
> +import java.util.*
Ah ? J'ai réutilisé le code de Discothèque, il utilise aussi le random de java, je vais changer là aussi du coup

2021-01-24 22:40 UTC, FrancoisDuchene commented on app/src/main/java/lufra/youpidapp/Discotheque.kt
>  import java.util.*
Attends j'ai pas compris, tu veux refractor quoi ici ?

2021-01-24 22:45 UTC, FrancoisDuchene commented
> Faut que tu rebases/merges.
j'ai peur de faire de la merde (je maitrise pas vraiment les rebase)
> Comme suggéré dans un commentaire, peut-être qu'il faudrait refactor les méthodes pour qu'on puisse passer directement l'id de resources, plutôt que passer un (pointeur vers) string qui doit ensuite être passé dans une Map. Mais later...
Je vais changer uniquement pour la méthode qui nous intéresse ici (```playOne```), à voir plus tard si il faut refractor d'autres parties
> La musique est un peu longue, et comme on sait, les blagues les plus courtes sont les meilleures ;)
C'était un peu la blague aussi, mais je vais diminuer à 30 secondes (là c'est 60)
> Aussi, j'ai pas bien compris, mais pourquoi on passe le mode de lecture en "l'un après l'autre", et pas en "en même temps" ?
10 secondes avant la fin de la musique, y a un "une caste inférieure" qui est lancé. Si c'est dans un autre mode que "en même temps", la musique est coupée pour lancer le nouveau son. Or je veux qu'il soit lancé pendant que la musique tourne. Maintenant je viens de me rendre compte que je reset jamais vers l'ancien mode

2021-01-24 23:41 UTC, Jimvy commented on app/src/main/java/data/PaperPlane.kt
> +class PaperPlane(
On pourrait la mettre dans un package View ou un truc du style alors...
Ou alors peut-être que c'est à BoiteFragment d'externaliser une partie de son code pour la simplifier (je sais pas trop comment rendre ça clean note)

2021-01-24 23:43 UTC, Jimvy commented on app/src/main/java/lufra/youpidapp/Discotheque.kt
>  import java.util.*
Retirer le Log ?

2021-01-24 23:49 UTC, Jimvy commented
> > Faut que tu rebases/merges.
> 
> j'ai peur de faire de la merde (je maitrise pas vraiment les rebase)

No problem, merge alors
> > Comme suggéré dans un commentaire, peut-être qu'il faudrait refactor les méthodes pour qu'on puisse passer directement l'id de resources, plutôt que passer un (pointeur vers) string qui doit ensuite être passé dans une Map. Mais later...
>
> Je vais changer uniquement pour la méthode qui nous intéresse ici (`playOne`), à voir plus tard si il faut refractor d'autres parties

👍
> > La musique est un peu longue, et comme on sait, les blagues les plus courtes sont les meilleures ;)
>
> C'était un peu la blague aussi, mais je vais diminuer à 30 secondes (là c'est 60)

Ou même 15-20, mais bon.

> > Aussi, j'ai pas bien compris, mais pourquoi on passe le mode de lecture en "l'un après l'autre", et pas en "en même temps" ?
>
> 10 secondes avant la fin de la musique, y a un "une caste inférieure" qui est lancé. Si c'est dans un autre mode que "en même temps", la musique est coupée pour lancer le nouveau son. Or je veux qu'il soit lancé pendant que la musique tourne. Maintenant je viens de me rendre compte que je reset jamais vers l'ancien mode

Oui oui, ma question c'était pourquoi "one after one" et pas "en même temps" : ici ça marche car "one after one" ne coupe pas le son en cours (cf #24 ), mais en vrai "en même temps" serait plus accurate.

2021-01-25 00:16 UTC, FrancoisDuchene commented
> No problem, merge alors

je fais dès que Luis voie les changements 😉 
 
> > > Comme suggéré dans un commentaire, peut-être qu'il faudrait refactor les méthodes pour qu'on puisse passer directement l'id de resources, plutôt que passer un (pointeur vers) string qui doit ensuite être passé dans une Map. Mais later...
> > 
> > 
> > Je vais changer uniquement pour la méthode qui nous intéresse ici (`playOne`), à voir plus tard si il faut refractor d'autres parties

> Oui oui, ma question c'était pourquoi "one after one" et pas "en même temps" : ici ça marche car "one after one" ne coupe pas le son en cours (cf #24 ), mais en vrai "en même temps" serait plus accurate.

bon ben finalement j'ai fait pour playStack et playList aussi. J'ai ajouté un son de pluie qui joue en même temps que la musique. Au lieu d'appeler ```playOne``` pour jouer la musique, j’appelle ```playStack```.

2021-01-25 17:16 UTC, TGLuis approved these changes
Ok for me :)

2021-01-25 21:28 UTC, merged